version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - cd lambdapi
      - pip install -r requirements.txt -t .
  build:
    commands:
      - aws cloudformation package \
          --template-file lambdapi/template.yml \
          --output-template-file lambdapi/template-out.yml \
          --s3-bucket projectautomate1 \
          --s3-prefix lambdadepolyment

artifacts:
  files:
    - lambdapi/template-out.yml
